name: Build

on:
  push:
    branches: [ "main", "nix-workflows" ]
  pull_request:
    branches: [ "main", "nix-workflows" ]

permissions:
  contents: read

jobs:
  build-cabal:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install hlint hpack

    - name: Hpack
      run: hpack

    - name: Install Haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.2'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks

    - name: Hlint
      run: hlint .

    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
      
    - name: Run tests
      run: cabal test all

  build-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: cachix/cachix-action@v12
      with:
        name: myme
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build
      run: nix build -L
